MusicFolder = "/data/music"
PlaylistsPath = "/data/playlists:**/**"
DataFolder = "/data/navidrome"
ScanSchedule = "@every 360m"
BaseUrl = ""
Address = "0.0.0.0"
Port = 80
EnableTranscodingConfig = true
TranscodingCacheSize = "500MB"
ImageCacheSize = "100MB"
AutoImportPlaylists = true
UILoginBackgroundUrl = "https://source.unsplash.com/random/1600x900?music"
UIWelcomeMessage = "Welcome to CasjaysDev music server"
EnableCoverAnimation = true
RecentlyAddedByModTime = false
CoverArtPriority = "embedded, cover.*, folder.*, front.*"
CoverJpegQuality = 75
EnableDownloads = true
SessionTimeout = "720h"
AuthRequestLimit = 5
AuthWindowLength = "20s"
EnableGravatar = false
EnableExternalServices = true
EnableFavourites = true
EnableStarRating = true
EnableUserEditing = true
DefaultTheme = "Dark"
PasswordEncryptionKey = ""
#GATrackingID = ""

# [Scanner]
Extractor = "taglib"

# [LastFM]
#Enabled = true
#ApiKey = ""
#Secret = ""
#Language = "en"

# [ListenBrainz]
Enabled = true

